### ISSUE TITLE
Bổ sung quản lý assets cho matching route và URL

### ISSUE THREAD

**Issue by nguyentranchung** [botble/laravel-assets#1]
có thể thêm 2 khóa trong config, nếu khớp url hay route sẽ tự động add or remove như vậy quản lý sẽ tập trung và cool hơn, anh gợi ý như ở dưới
```
'route' => [
    'login' => [
        'javascript' => [
            'key-trong-resource-javascript-1' => 'add',
            'key-trong-resource-javascript-2' => 'remove',
        ],
        'stylesheets' => [
            'key-trong-resource-stylesheets-1' => 'add',
            'key-trong-resource-stylesheets-2' => 'remove',
        ]
    ],
    'route-2' => ...
],
'url' => [
    'posts/*' => giống route
    ...
]
```

**Comment by sangnguyenplus** [comment]
Chơi magic kiểu này nó khó quản lý hơn đó anh. Hợp lý nhất là add/remove trong controller. Chơi kiểu này thấy ghê ghê và khó nâng cấp. 
Việc thay đổi tên/đường dẫn của route không nên phụ thuộc vào assets. 2 cái ràng buộc nhau thì lúc sửa cái này phải chú ý cái kia.

=> Phiền lắm.

**Comment by nguyentranchung** [comment]
tất cả cấu hình em đều merge vào 1 biến rồi lấy ra, đâu có ảnh hưởng nhiều lắm đâu em nhỉ

**Comment by sangnguyenplus** [comment]
Nhưng người ta sẽ khó quản lý được assets load thế nào, lỡ đặt cái route trùng định dạng cái nó chèn 1 nùi hoặc thiếu assets.

Lúc tạo thêm route mới phải chú ý coi có hay chưa config cho assets. 2 cái này không nên phụ thuộc nhau. Xu hướng hiện nay là họ làm giảm phụ thuộc mà. Controller là module cấp cao, sao lại phụ thuộc vào assets (module cấp thấp) được :D
