### ISSUE TITLE
Không nên gọi trực tiếp env trong code, hãy nạp trong config

### ISSUE THREAD

**Issue by nguyentranchung** [botble/laravel-assets#2]
https://github.com/botble/laravel-assets/blob/a67a30e521607a2e22801c52ef788f1f22081da1/src/Assets.php#L68

**Comment by nguyentranchung** [comment]
nếu người dùng enable mà quên k set ASSET_VERSION vậy là mỗi lần f5 website đều load dưới dạng no cache, nên chỗ này tối ưu lại nhé

**Comment by sangnguyenplus** [comment]
@nguyentranchung tạo PR đi đại ka. Cái này bỏ vào config là xong :D

**Comment by sangnguyenplus** [comment]
Fixed!

**Comment by nguyentranchung** [comment]
@sangnguyenplus lúc commit fix cho issue nào trong summary nên thêm # issue id để tracking nhé

**Comment by sangnguyenplus** [comment]
@nguyentranchung Em không có rule đó nhé :D Cái đó chỉ áp dụng cho project của cty thôi :D
