### ISSUE TITLE
Thống nhất về đặt key số nhiều

### ISSUE THREAD

**Issue by nguyentranchung** [botble/laravel-assets#3]
https://github.com/botble/laravel-assets/blob/a67a30e521607a2e22801c52ef788f1f22081da1/config/assets.php#L13

javascript => số ít
stylesheets => số nhiều
nên thống nhất lại

**Comment by sangnguyenplus** [comment]
Ai nói a javascript là số ít thế. Haha

**Comment by nguyentranchung** [comment]
@sangnguyenplus tài liệu nào nói javascript là số nhiều?

**Comment by sangnguyenplus** [comment]
@nguyentranchung vì nó là tên riêng nên em không nói nó là số nhiều hay số ít cả :D

**Comment by sangnguyenplus** [comment]
@nguyentranchung, it's fixed in version `1.0.4`

Thank you!
